bSecure.RegionRestrictions = {}
bSecure.RegionRestrictions.DisallowedCountries = {}

bSecure.RegionRestrictions.Countries = {
	["AF"] = "Afghanistan",
	["AL"] = "Albania",
	["DZ"] = "Algeria",
	["AX"] = "Aland Islands",
	["AS"] = "American Samoa",
	["AI"] = "Anguilla",
	["AD"] = "Andorra",
	["AO"] = "Angola",
	["AN"] = "Antilles - Netherlands",
	["AG"] = "Antigua and Barbuda",
	["AQ"] = "Antarctica",
	["AR"] = "Argentina",
	["AM"] = "Armenia",
	["AU"] = "Australia",
	["AT"] = "Austria",
	["AW"] = "Aruba",
	["AZ"] = "Azerbaijan",
	["BA"] = "Bosnia and Herzegovina",
	["BB"] = "Barbados",
	["BD"] = "Bangladesh",
	["BE"] = "Belgium",
	["BF"] = "Burkina Faso",
	["BG"] = "Bulgaria",
	["BH"] = "Bahrain",
	["BI"] = "Burundi",
	["BJ"] = "Benin",
	["BM"] = "Bermuda",
	["BN"] = "Brunei Darussalam",
	["BO"] = "Bolivia",
	["BR"] = "Brazil",
	["BS"] = "Bahamas",
	["BT"] = "Bhutan",
	["BV"] = "Bouvet Island",
	["BW"] = "Botswana",
	["BV"] = "Belarus",
	["BZ"] = "Belize",
	["KH"] = "Cambodia",
	["CM"] = "Cameroon",
	["CA"] = "Canada",
	["CV"] = "Cape Verde",
	["CF"] = "Central African Republic",
	["TD"] = "Chad",
	["CL"] = "Chile",
	["CN"] = "China",
	["CX"] = "Christmas Island",
	["CC"] = "Cocos (Keeling) Islands",
	["CO"] = "Colombia",
	["CG"] = "Congo",
	["CI"] = "Cote D'Ivoire (Ivory Coast)",
	["CK"] = "Cook Islands",
	["CR"] = "Costa Rica",
	["HR"] = "Croatia (Hrvatska)",
	["CU"] = "Cuba",
	["CY"] = "Cyprus",
	["CZ"] = "Czech Republic",
	["CD"] = "Democratic Republic of the Congo",
	["DJ"] = "Djibouti",
	["DK"] = "Denmark",
	["DM"] = "Dominica",
	["DO"] = "Dominican Republic",
	["EC"] = "Ecuador",
	["EG"] = "Egypt",
	["SV"] = "El Salvador",
	["TP"] = "East Timor",
	["EE"] = "Estonia",
	["GQ"] = "Equatorial Guinea",
	["ER"] = "Eritrea",
	["ET"] = "Ethiopia",
	["FI"] = "Finland",
	["FJ"] = "Fiji",
	["FK"] = "Falkland Islands (Malvinas)",
	["FM"] = "Federated States of Micronesia",
	["FO"] = "Faroe Islands",
	["FR"] = "France",
	["FX"] = "France, Metropolitan",
	["GF"] = "French Guiana",
	["PF"] = "French Polynesia",
	["GA"] = "Gabon",
	["GM"] = "Gambia",
	["DE"] = "Germany",
	["GH"] = "Ghana",
	["GI"] = "Gibraltar",
	["GB"] = "Great Britain (UK)",
	["GD"] = "Grenada",
	["GE"] = "Georgia",
	["GR"] = "Greece",
	["GL"] = "Greenland",
	["GN"] = "Guinea",
	["GP"] = "Guadeloupe",
	["GS"] = "S. Georgia and S. Sandwich Islands",
	["GT"] = "Guatemala",
	["GU"] = "Guam",
	["GW"] = "Guinea-Bissau",
	["GY"] = "Guyana",
	["HK"] = "Hong Kong",
	["HM"] = "Heard Island and McDonald Islands",
	["HN"] = "Honduras",
	["HT"] = "Haiti",
	["HU"] = "Hungary",
	["ID"] = "Indonesia",
	["IE"] = "Ireland",
	["IL"] = "Israel",
	["IN"] = "India",
	["IO"] = "British Indian Ocean Territory",
	["IQ"] = "Iraq",
	["IR"] = "Iran",
	["IT"] = "Italy",
	["JM"] = "Jamaica",
	["JO"] = "Jordan",
	["JP"] = "Japan",
	["KE"] = "Kenya",
	["KG"] = "Kyrgyzstan",
	["KI"] = "Kiribati",
	["KM"] = "Comoros",
	["KN"] = "Saint Kitts and Nevis",
	["KP"] = "Korea (North)",
	["KR"] = "Korea (South)",
	["KW"] = "Kuwait",
	["KY"] = "Cayman Islands",
	["KZ"] = "Kazakhstan",
	["LA"] = "Laos",
	["LB"] = "Lebanon",
	["LC"] = "Saint Lucia",
	["LI"] = "Liechtenstein",
	["LK"] = "Sri Lanka",
	["LR"] = "Liberia",
	["LS"] = "Lesotho",
	["LT"] = "Lithuania",
	["LU"] = "Luxembourg",
	["LV"] = "Latvia",
	["LY"] = "Libya",
	["MK"] = "Macedonia",
	["MO"] = "Macao",
	["MG"] = "Madagascar",
	["MY"] = "Malaysia",
	["ML"] = "Mali",
	["MW"] = "Malawi",
	["MR"] = "Mauritania",
	["MH"] = "Marshall Islands",
	["MQ"] = "Martinique",
	["MU"] = "Mauritius",
	["YT"] = "Mayotte",
	["MT"] = "Malta",
	["MX"] = "Mexico",
	["MA"] = "Morocco",
	["MC"] = "Monaco",
	["MD"] = "Moldova",
	["MN"] = "Mongolia",
	["MM"] = "Myanmar",
	["MP"] = "Northern Mariana Islands",
	["MS"] = "Montserrat",
	["MV"] = "Maldives",
	["MZ"] = "Mozambique",
	["NA"] = "Namibia",
	["NC"] = "New Caledonia",
	["NE"] = "Niger",
	["NF"] = "Norfolk Island",
	["NG"] = "Nigeria",
	["NI"] = "Nicaragua",
	["NL"] = "Netherlands",
	["NO"] = "Norway",
	["NP"] = "Nepal",
	["NR"] = "Nauru",
	["NU"] = "Niue",
	["NZ"] = "New Zealand (Aotearoa)",
	["OM"] = "Oman",
	["PA"] = "Panama",
	["PE"] = "Peru",
	["PG"] = "Papua New Guinea",
	["PH"] = "Philippines",
	["PK"] = "Pakistan",
	["PL"] = "Poland",
	["PM"] = "Saint Pierre and Miquelon",
	["CS"] = "Serbia and Montenegro",
	["PN"] = "Pitcairn",
	["PR"] = "Puerto Rico",
	["PS"] = "Palestinian Territory",
	["PT"] = "Portugal",
	["PW"] = "Palau",
	["PY"] = "Paraguay",
	["QA"] = "Qatar",
	["RE"] = "Reunion",
	["RO"] = "Romania",
	["RU"] = "Russian Federation",
	["RW"] = "Rwanda",
	["SA"] = "Saudi Arabia",
	["WS"] = "Samoa",
	["SH"] = "Saint Helena",
	["VC"] = "Saint Vincent and the Grenadines",
	["SM"] = "San Marino",
	["ST"] = "Sao Tome and Principe",
	["SN"] = "Senegal",
	["SC"] = "Seychelles",
	["SL"] = "Sierra Leone",
	["SG"] = "Singapore",
	["SK"] = "Slovakia",
	["SI"] = "Slovenia",
	["SB"] = "Solomon Islands",
	["SO"] = "Somalia",
	["ZA"] = "South Africa",
	["ES"] = "Spain",
	["SD"] = "Sudan",
	["SR"] = "Suriname",
	["SJ"] = "Svalbard and Jan Mayen",
	["SE"] = "Sweden",
	["CH"] = "Switzerland",
	["SY"] = "Syria",
	["SU"] = "USSR (former)",
	["SZ"] = "Swaziland",
	["TW"] = "Taiwan",
	["TZ"] = "Tanzania",
	["TJ"] = "Tajikistan",
	["TH"] = "Thailand",
	["TL"] = "Timor-Leste",
	["TG"] = "Togo",
	["TK"] = "Tokelau",
	["TO"] = "Tonga",
	["TT"] = "Trinidad and Tobago",
	["TN"] = "Tunisia",
	["TR"] = "Turkey",
	["TM"] = "Turkmenistan",
	["TC"] = "Turks and Caicos Islands",
	["TV"] = "Tuvalu",
	["UA"] = "Ukraine",
	["UG"] = "Uganda",
	["AE"] = "United Arab Emirates",
	["UK"] = "United Kingdom",
	["US"] = "United States",
	["UM"] = "United States Minor Outlying Islands",
	["UY"] = "Uruguay",
	["UZ"] = "Uzbekistan",
	["VU"] = "Vanuatu",
	["VA"] = "Vatican City State",
	["VE"] = "Venezuela",
	["VG"] = "Virgin Islands (British)",
	["VI"] = "Virgin Islands (U.S.)",
	["VN"] = "Viet Nam",
	["WF"] = "Wallis and Futuna",
	["EH"] = "Western Sahara",
	["YE"] = "Yemen",
	["YU"] = "Yugoslavia (former)",
	["ZM"] = "Zambia",
	["ZR"] = "Zaire (former)",
	["ZW"] = "Zimbabwe",
}

bSecure.RegionRestrictions.iCountries = {
	"Afghanistan",
	"Albania",
	"Algeria",
	"Aland Islands",
	"American Samoa",
	"Anguilla",
	"Andorra",
	"Angola",
	"Antilles - Netherlands",
	"Antigua and Barbuda",
	"Antarctica",
	"Argentina",
	"Armenia",
	"Australia",
	"Austria",
	"Aruba",
	"Azerbaijan",
	"Bosnia and Herzegovina",
	"Barbados",
	"Bangladesh",
	"Belgium",
	"Burkina Faso",
	"Bulgaria",
	"Bahrain",
	"Burundi",
	"Benin",
	"Bermuda",
	"Brunei Darussalam",
	"Bolivia",
	"Brazil",
	"Bahamas",
	"Bhutan",
	"Bouvet Island",
	"Botswana",
	"Belarus",
	"Belize",
	"Cambodia",
	"Cameroon",
	"Canada",
	"Cape Verde",
	"Central African Republic",
	"Chad",
	"Chile",
	"China",
	"Christmas Island",
	"Cocos (Keeling) Islands",
	"Colombia",
	"Congo",
	"Cote D'Ivoire (Ivory Coast)",
	"Cook Islands",
	"Costa Rica",
	"Croatia (Hrvatska)",
	"Cuba",
	"Cyprus",
	"Czech Republic",
	"Democratic Republic of the Congo",
	"Djibouti",
	"Denmark",
	"Dominica",
	"Dominican Republic",
	"Ecuador",
	"Egypt",
	"El Salvador",
	"East Timor",
	"Estonia",
	"Equatorial Guinea",
	"Eritrea",
	"Ethiopia",
	"Finland",
	"Fiji",
	"Falkland Islands (Malvinas)",
	"Federated States of Micronesia",
	"Faroe Islands",
	"France",
	"France, Metropolitan",
	"French Guiana",
	"French Polynesia",
	"Gabon",
	"Gambia",
	"Germany",
	"Ghana",
	"Gibraltar",
	"Great Britain (UK)",
	"Grenada",
	"Georgia",
	"Greece",
	"Greenland",
	"Guinea",
	"Guadeloupe",
	"S. Georgia and S. Sandwich Islands",
	"Guatemala",
	"Guam",
	"Guinea-Bissau",
	"Guyana",
	"Hong Kong",
	"Heard Island and McDonald Islands",
	"Honduras",
	"Haiti",
	"Hungary",
	"Indonesia",
	"Ireland",
	"Israel",
	"India",
	"British Indian Ocean Territory",
	"Iraq",
	"Iran",
	"Italy",
	"Jamaica",
	"Jordan",
	"Japan",
	"Kenya",
	"Kyrgyzstan",
	"Kiribati",
	"Comoros",
	"Saint Kitts and Nevis",
	"Korea (North)",
	"Korea (South)",
	"Kuwait",
	"Cayman Islands",
	"Kazakhstan",
	"Laos",
	"Lebanon",
	"Saint Lucia",
	"Liechtenstein",
	"Sri Lanka",
	"Liberia",
	"Lesotho",
	"Lithuania",
	"Luxembourg",
	"Latvia",
	"Libya",
	"Macedonia",
	"Macao",
	"Madagascar",
	"Malaysia",
	"Mali",
	"Malawi",
	"Mauritania",
	"Marshall Islands",
	"Martinique",
	"Mauritius",
	"Mayotte",
	"Malta",
	"Mexico",
	"Morocco",
	"Monaco",
	"Moldova",
	"Mongolia",
	"Myanmar",
	"Northern Mariana Islands",
	"Montserrat",
	"Maldives",
	"Mozambique",
	"Namibia",
	"New Caledonia",
	"Niger",
	"Norfolk Island",
	"Nigeria",
	"Nicaragua",
	"Netherlands",
	"Norway",
	"Nepal",
	"Nauru",
	"Niue",
	"New Zealand (Aotearoa)",
	"Oman",
	"Panama",
	"Peru",
	"Papua New Guinea",
	"Philippines",
	"Pakistan",
	"Poland",
	"Saint Pierre and Miquelon",
	"Serbia and Montenegro",
	"Pitcairn",
	"Puerto Rico",
	"Palestinian Territory",
	"Portugal",
	"Palau",
	"Paraguay",
	"Qatar",
	"Reunion",
	"Romania",
	"Russian Federation",
	"Rwanda",
	"Saudi Arabia",
	"Samoa",
	"Saint Helena",
	"Saint Vincent and the Grenadines",
	"San Marino",
	"Sao Tome and Principe",
	"Senegal",
	"Seychelles",
	"Sierra Leone",
	"Singapore",
	"Slovakia",
	"Slovenia",
	"Solomon Islands",
	"Somalia",
	"South Africa",
	"Spain",
	"Sudan",
	"Suriname",
	"Svalbard and Jan Mayen",
	"Sweden",
	"Switzerland",
	"Syria",
	"USSR (former)",
	"Swaziland",
	"Taiwan",
	"Tanzania",
	"Tajikistan",
	"Thailand",
	"Timor-Leste",
	"Togo",
	"Tokelau",
	"Tonga",
	"Trinidad and Tobago",
	"Tunisia",
	"Turkey",
	"Turkmenistan",
	"Turks and Caicos Islands",
	"Tuvalu",
	"Ukraine",
	"Uganda",
	"United Arab Emirates",
	"United Kingdom",
	"United States",
	"United States Minor Outlying Islands",
	"Uruguay",
	"Uzbekistan",
	"Vanuatu",
	"Vatican City State",
	"Venezuela",
	"Virgin Islands (British)",
	"Virgin Islands (U.S.)",
	"Viet Nam",
	"Wallis and Futuna",
	"Western Sahara",
	"Yemen",
	"Yugoslavia (former)",
	"Zambia",
	"Zaire (former)",
	"Zimbabwe",
}

bSecure.RegionRestrictions.iCountryCodes = {
	"AF",
	"AL",
	"DZ",
	"AX",
	"AS",
	"AI",
	"AD",
	"AO",
	"AN",
	"AG",
	"AQ",
	"AR",
	"AM",
	"AU",
	"AT",
	"AW",
	"AZ",
	"BA",
	"BB",
	"BD",
	"BE",
	"BF",
	"BG",
	"BH",
	"BI",
	"BJ",
	"BM",
	"BN",
	"BO",
	"BR",
	"BS",
	"BT",
	"BV",
	"BW",
	"BV",
	"BZ",
	"KH",
	"CM",
	"CA",
	"CV",
	"CF",
	"TD",
	"CL",
	"CN",
	"CX",
	"CC",
	"CO",
	"CG",
	"CI",
	"CK",
	"CR",
	"HR",
	"CU",
	"CY",
	"CZ",
	"CD",
	"DJ",
	"DK",
	"DM",
	"DO",
	"EC",
	"EG",
	"SV",
	"TP",
	"EE",
	"GQ",
	"ER",
	"ET",
	"FI",
	"FJ",
	"FK",
	"FM",
	"FO",
	"FR",
	"FX",
	"GF",
	"PF",
	"GA",
	"GM",
	"DE",
	"GH",
	"GI",
	"GB",
	"GD",
	"GE",
	"GR",
	"GL",
	"GN",
	"GP",
	"GS",
	"GT",
	"GU",
	"GW",
	"GY",
	"HK",
	"HM",
	"HN",
	"HT",
	"HU",
	"ID",
	"IE",
	"IL",
	"IN",
	"IO",
	"IQ",
	"IR",
	"IT",
	"JM",
	"JO",
	"JP",
	"KE",
	"KG",
	"KI",
	"KM",
	"KN",
	"KP",
	"KR",
	"KW",
	"KY",
	"KZ",
	"LA",
	"LB",
	"LC",
	"LI",
	"LK",
	"LR",
	"LS",
	"LT",
	"LU",
	"LV",
	"LY",
	"MK",
	"MO",
	"MG",
	"MY",
	"ML",
	"MW",
	"MR",
	"MH",
	"MQ",
	"MU",
	"YT",
	"MT",
	"MX",
	"MA",
	"MC",
	"MD",
	"MN",
	"MM",
	"MP",
	"MS",
	"MV",
	"MZ",
	"NA",
	"NC",
	"NE",
	"NF",
	"NG",
	"NI",
	"NL",
	"NO",
	"NP",
	"NR",
	"NU",
	"NZ",
	"OM",
	"PA",
	"PE",
	"PG",
	"PH",
	"PK",
	"PL",
	"PM",
	"CS",
	"PN",
	"PR",
	"PS",
	"PT",
	"PW",
	"PY",
	"QA",
	"RE",
	"RO",
	"RU",
	"RW",
	"SA",
	"WS",
	"SH",
	"VC",
	"SM",
	"ST",
	"SN",
	"SC",
	"SL",
	"SG",
	"SK",
	"SI",
	"SB",
	"SO",
	"ZA",
	"ES",
	"SD",
	"SR",
	"SJ",
	"SE",
	"CH",
	"SY",
	"SU",
	"SZ",
	"TW",
	"TZ",
	"TJ",
	"TH",
	"TL",
	"TG",
	"TK",
	"TO",
	"TT",
	"TN",
	"TR",
	"TM",
	"TC",
	"TV",
	"UA",
	"UG",
	"AE",
	"UK",
	"US",
	"UM",
	"UY",
	"UZ",
	"VU",
	"VA",
	"VE",
	"VG",
	"VI",
	"VN",
	"WF",
	"EH",
	"YE",
	"YU",
	"ZM",
	"ZR",
	"ZW",
}